[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solocker = "3xf2u5H4qGaQJbrW5gkcpE38NrXJN5Duru7wtdkjHbcX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/tid/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
